-- MySQL Script generated by MySQL Workbench
-- Tue Nov  8 17:46:46 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema zal3-zkowalsem_1
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema zal3-zkowalsem_1
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `zal3-zkowalsem_1` DEFAULT CHARACTER SET utf8 ;
USE `zal3-zkowalsem_1` ;

-- -----------------------------------------------------
-- Table `zal3-zkowalsem_1`.`t_compte_cpt`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `zal3-zkowalsem_1`.`t_compte_cpt` (
  `cpt_id` INT NOT NULL AUTO_INCREMENT,
  `cpt_pseudo` VARCHAR(20) CHARACTER SET 'utf8' COLLATE 'utf8_bin' NOT NULL,
  `cpt_mdp` CHAR(64) CHARACTER SET 'utf8' COLLATE 'utf8_bin' NOT NULL,
  PRIMARY KEY (`cpt_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `zal3-zkowalsem_1`.`t_quiz_qui`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `zal3-zkowalsem_1`.`t_quiz_qui` (
  `qui_id` INT NOT NULL AUTO_INCREMENT,
  `qui_intitule` VARCHAR(100) NOT NULL,
  `qui_image` VARCHAR(200) NOT NULL,
  `qui_etat` CHAR(1) NOT NULL,
  `cpt_id` INT NOT NULL,
  PRIMARY KEY (`qui_id`),
  INDEX `fk_t_quiz_qui_t_compte_cpt1_idx` (`cpt_id` ASC) VISIBLE,
  CONSTRAINT `fk_t_quiz_qui_t_compte_cpt1`
    FOREIGN KEY (`cpt_id`)
    REFERENCES `zal3-zkowalsem_1`.`t_compte_cpt` (`cpt_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `zal3-zkowalsem_1`.`t_match_mtc`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `zal3-zkowalsem_1`.`t_match_mtc` (
  `mtc_id` INT NOT NULL AUTO_INCREMENT,
  `mtc_int` VARCHAR(100) NOT NULL,
  `mtc_scoreactif` DOUBLE NOT NULL,
  `mtc_date_debut` DATETIME NOT NULL,
  `mtc_date_fin` DATETIME NULL,
  `mtc_etat_match` CHAR(1) NOT NULL,
  `mtc_etat_corrige` CHAR(1) NOT NULL,
  `mtc_codematch` CHAR(8) NOT NULL,
  `qui_id` INT NOT NULL,
  `cpt_id` INT NOT NULL,
  PRIMARY KEY (`mtc_id`),
  UNIQUE INDEX `mtc_codematch_UNIQUE` (`mtc_codematch` ASC) VISIBLE,
  INDEX `fk_t_match_mtc_t_quiz_qui1_idx` (`qui_id` ASC) VISIBLE,
  INDEX `fk_t_match_mtc_t_compte_cpt1_idx` (`cpt_id` ASC) VISIBLE,
  CONSTRAINT `fk_t_match_mtc_t_quiz_qui1`
    FOREIGN KEY (`qui_id`)
    REFERENCES `zal3-zkowalsem_1`.`t_quiz_qui` (`qui_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_t_match_mtc_t_compte_cpt1`
    FOREIGN KEY (`cpt_id`)
    REFERENCES `zal3-zkowalsem_1`.`t_compte_cpt` (`cpt_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `zal3-zkowalsem_1`.`t_joueur_jou`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `zal3-zkowalsem_1`.`t_joueur_jou` (
  `jou_id` INT NOT NULL AUTO_INCREMENT,
  `jou_pseudo` VARCHAR(20) CHARACTER SET 'utf8' COLLATE 'utf8_bin' NOT NULL,
  `jou_score` DOUBLE NOT NULL,
  `jou_heurevalidation` DATETIME NULL,
  `mtc_id` INT NOT NULL,
  PRIMARY KEY (`jou_id`),
  INDEX `fk_t_joueur_jou_t_match_mtc1_idx` (`mtc_id` ASC) VISIBLE,
  CONSTRAINT `fk_t_joueur_jou_t_match_mtc1`
    FOREIGN KEY (`mtc_id`)
    REFERENCES `zal3-zkowalsem_1`.`t_match_mtc` (`mtc_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `zal3-zkowalsem_1`.`t_actu_act`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `zal3-zkowalsem_1`.`t_actu_act` (
  `act_id` INT NOT NULL AUTO_INCREMENT,
  `act_int` VARCHAR(100) NOT NULL,
  `act_date` DATE NOT NULL,
  `act_txt` VARCHAR(500) NOT NULL,
  `act_etat` CHAR(1) NOT NULL,
  `cpt_id` INT NOT NULL,
  PRIMARY KEY (`act_id`),
  INDEX `fk_act_actu_cpt_compte1_idx` (`cpt_id` ASC) VISIBLE,
  CONSTRAINT `fk_act_actu_cpt_compte1`
    FOREIGN KEY (`cpt_id`)
    REFERENCES `zal3-zkowalsem_1`.`t_compte_cpt` (`cpt_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `zal3-zkowalsem_1`.`t_question_qst`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `zal3-zkowalsem_1`.`t_question_qst` (
  `qst_id` INT NOT NULL AUTO_INCREMENT,
  `qst_etat` CHAR(1) NOT NULL,
  `qst_ordre` INT NOT NULL,
  `qst_texte` VARCHAR(500) NOT NULL,
  `qui_id` INT NOT NULL,
  PRIMARY KEY (`qst_id`),
  INDEX `fk_qst_question_qui_quiz1_idx` (`qui_id` ASC) VISIBLE,
  CONSTRAINT `fk_qst_question_qui_quiz1`
    FOREIGN KEY (`qui_id`)
    REFERENCES `zal3-zkowalsem_1`.`t_quiz_qui` (`qui_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `zal3-zkowalsem_1`.`t_reponse_rep`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `zal3-zkowalsem_1`.`t_reponse_rep` (
  `rep_id` INT NOT NULL AUTO_INCREMENT,
  `rep_libelle` VARCHAR(500) NOT NULL,
  `rep_ordre` INT NOT NULL,
  `rep_correct` CHAR(1) NOT NULL,
  `qst_id` INT NOT NULL,
  PRIMARY KEY (`rep_id`),
  INDEX `fk_rep_reponse_qst_question1_idx` (`qst_id` ASC) VISIBLE,
  CONSTRAINT `fk_rep_reponse_qst_question1`
    FOREIGN KEY (`qst_id`)
    REFERENCES `zal3-zkowalsem_1`.`t_question_qst` (`qst_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `zal3-zkowalsem_1`.`t_profil_pfl`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `zal3-zkowalsem_1`.`t_profil_pfl` (
  `cpt_id` INT NOT NULL AUTO_INCREMENT,
  `pfl_role` CHAR(1) NOT NULL,
  `pfl_nom` VARCHAR(60) NOT NULL,
  `pfl_prenom` VARCHAR(60) NOT NULL,
  `pfl_mail` VARCHAR(100) NOT NULL,
  `pfl_actif` CHAR(1) NOT NULL,
  PRIMARY KEY (`cpt_id`),
  CONSTRAINT `fk_t_profil_pfl_t_compte_cpt1`
    FOREIGN KEY (`cpt_id`)
    REFERENCES `zal3-zkowalsem_1`.`t_compte_cpt` (`cpt_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
